sudo: false
language: cpp
compiler:
  - clang++
  - g++

install:
  - if [ "$CXX" = "g++" ]; then export CXX="g++-5" CC="gcc-5"; fi
  - if [ "$CXX" = "clang++" ]; then export CXX="clang++-3.7" CC="clang-3.7"; fi

  - make CXX="${CXX}"
  - mkdir cbuild
  - cd cbuild
  - cmake .. -DCMAKE_INSTALL_PREFIX=install
  - make
  - make install
  - cd ..

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - llvm-toolchain-precise-3.7
      - llvm-toolchain-precise
    packages:
      - clang-3.7
      - g++-5
      - gcc-5

script:
  ./bin/test
