dist: trusty
sudo: false
group: beta
language: cpp
compiler:
  - clang++
  - g++

install:
  - make
  - mkdir cbuild
  - cd cbuild
  - cmake .. -DCMAKE_INSTALL_PREFIX=install
  - make
  - make install
  - cd ..

script:
  ./bin/test
