language: cpp
sudo: false
dist: trusty
group: beta
compiler:
  - clang++
  - g++
install:
  - make
  - mkdir cbuild
  - cd cbuild
  - cmake .. -DCMAKE_INSTALL_PREFIX=install
  - make
  - make install
  - cd ..
script:
  ./bin/test
