language: cpp
sudo: false
dist: trusty
group: beta
compiler:
- g++
- clang++
install:
- mkdir build
- cd build
- cmake .. -DCMAKE_INSTALL_PREFIX=install
- make
- make install
- cd -
script:
- cd build
- ctest
