language: cpp
group: beta
dist: trusty
sudo: false
compiler:
- g++
- clang++
before_install:
- cd thirdpatry/googletest/googletest
- cmake -DCMAKE_BUILD_TYPE=RELEASE .
- make
- cd -
- mkdir build
- cd build
install:
- cmake .. -DCMAKE_INSTALL_PREFIX=install -DENABLE_TEST=ON
- make
- make install
script:
- ctest
